<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-06-22T02:29:15Z" name="Suite" finished-at="2020-06-22T02:29:31Z" duration-ms="16345">
    <groups>
    </groups>
    <test started-at="2020-06-22T02:29:15Z" name="Test" finished-at="2020-06-22T02:29:20Z" duration-ms="5483">
      <class name="testINT.BaseClass">
        <test-method is-config="true" signature="driverInst(java.lang.String)[pri:0, instance:testINT.BaseClass@5fbdfdcf]" started-at="2020-06-22T07:59:15Z" name="driverInst" finished-at="2020-06-22T07:59:18Z" duration-ms="3222" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverInst -->
        <test-method signature="getTest()[pri:0, instance:testINT.BaseClass@5fbdfdcf]" started-at="2020-06-22T07:59:18Z" name="getTest" finished-at="2020-06-22T07:59:19Z" duration-ms="1339" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at testINT.BaseClass.getTest(BaseClass.java:58)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:567)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTest -->
        <test-method is-config="true" signature="afterTest(org.testng.ITestResult)[pri:0, instance:testINT.BaseClass@5fbdfdcf]" started-at="2020-06-22T07:59:19Z" name="afterTest" finished-at="2020-06-22T07:59:20Z" duration-ms="903" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getTest status=FAILURE method=BaseClass.getTest()[pri:0, instance:testINT.BaseClass@5fbdfdcf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testINT.BaseClass -->
    </test> <!-- Test -->
    <test started-at="2020-06-22T02:29:20Z" name="Test1" finished-at="2020-06-22T02:29:31Z" duration-ms="10835">
      <class name="testINT.BaseClass">
        <test-method is-config="true" signature="driverInst(java.lang.String)[pri:0, instance:testINT.BaseClass@614ca7df]" started-at="2020-06-22T07:59:20Z" name="driverInst" finished-at="2020-06-22T07:59:26Z" duration-ms="5578" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverInst -->
        <test-method signature="getTest()[pri:0, instance:testINT.BaseClass@614ca7df]" started-at="2020-06-22T07:59:26Z" name="getTest" finished-at="2020-06-22T07:59:30Z" duration-ms="4390" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at testINT.BaseClass.getTest(BaseClass.java:58)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:567)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTest -->
        <test-method is-config="true" signature="afterTest(org.testng.ITestResult)[pri:0, instance:testINT.BaseClass@614ca7df]" started-at="2020-06-22T07:59:30Z" name="afterTest" finished-at="2020-06-22T07:59:31Z" duration-ms="864" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getTest status=FAILURE method=BaseClass.getTest()[pri:0, instance:testINT.BaseClass@614ca7df] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testINT.BaseClass -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
